# Generated by Django 2.0.7 on 2018-07-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
