# Generated by Django 2.0.7 on 2018-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knack', '0002_resource_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('hash', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('blog', models.CharField(default='', max_length=150)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
