# Generated by Django 2.0.7 on 2018-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knack', '0003_blog_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('hash', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('blog', models.CharField(default='', max_length=150)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='blog',
            name='homepage_hash',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
