# Generated by Django 2.0.7 on 2018-08-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knack', '0004_auto_20180728_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='forkof',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='forkof',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
